---
- name: install required packages
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: "present"
    install_recommends: yes
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg2"
    - "software-properties-common"

- name: add GPG key
  apt_key:
    id: "{{ docker_key_id }}"
    keyserver: "{{ docker_key_server }}"

- name: add apt repository
  shell: add-apt-repository "{{ docker_repository }} {{ ansible_lsb.codename }} edge"

- name: update apt
  apt:
    update_cache: yes

- name: install docker-ce
  apt:
    name: "docker-ce"
    update_cache: yes
    state: "present"